#VIA_ENABLE = yes
BOARD = GENERIC_RP_RP2040
EEPROM_DRIVER = wear_leveling
DIP_SWITCH_MAP_ENABLE = yes

# Backlight
BACKLIGHT_ENABLE = yes
BACKLIGHT_PIN = GP28
BACKLIGHT_LEVELS = 10
BACKLIGHT_DRIVER = pwm

#RGBLIGHT_ENABLE = yes
#RGBLIGHT_LED_COUNT = 11
#RGBLIGHT_DRIVER = ws2812
#WS2812_DRIVER = vendor
#WS2812_DI_PIN = GP29

# Encoder
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
